version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "7799:7799"
    environment:
      MONGODB_URI: "mongodb+srv://admin:admin@cluster0.alq91.mongodb.net/golang_online_books?retryWrites=true&w=majority&appName=Cluster0"
  frontend:
    build: ./frontend
    ports:
      - "9090:9090"
